<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Rental;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
        $query = Customer::query();

        if ($request->search) {
            $query->where('name', 'like', "%{$request->search}%")
                ->orWhere('phone', 'like', "%{$request->search}%")
                ->orWhere('license_number', 'like', "%{$request->search}%");
        }

        $customers = $query->withCount('rentals')->latest()->paginate(20);

        // For each customer, find their most frequent shop
        foreach ($customers as $customer) {
            $shopRentals = Rental::where('customer_id', $customer->id)
                ->select('user_id', DB::raw('COUNT(*) as count'))
                ->groupBy('user_id')
                ->orderBy('count', 'desc')
                ->first();

            if ($shopRentals && $shopRentals->user_id) {
                $shop = \App\Models\User::find($shopRentals->user_id);
                $customer->primary_shop = $shop ? $shop->name : '—';
            } else {
                $customer->primary_shop = '—';
            }

            // Extract city from address
            if ($customer->address) {
                $parts = explode(',', $customer->address);
                $customer->city = count($parts) > 1 ? trim($parts[count($parts) - 2]) : trim($parts[0]);
            } else {
                $customer->city = '—';
            }
        }

        $totalShops = User::where('role', 'user')->count();
        $customers = Customer::withCount('rentals')->latest()->paginate(20);

        return view('admin.customers.index', compact('customers', 'totalShops'));
    }

    public function show($id)
    {
        $customer = Customer::with(['rentals' => function ($q) {
            $q->with(['user', 'vehicle'])->latest()->limit(20);
        }])->findOrFail($id);

        $totalRentals = $customer->rentals()->count();
        $completedRentals = $customer->rentals()->where('status', 'completed')->count();
        $totalSpent = $customer->rentals()->where('status', 'completed')->sum('total_price');

        // Calculate verification income generated by this customer
        $verifRentals = $customer->rentals()->whereNotNull('verification_completed_at')->get();
        $income = 0;
        foreach ($verifRentals as $rental) {
            $income += $rental->is_verification_cached ? 3 : 1;
        }

        // Get all shops this customer visited
        $shopsVisited = \App\Models\User::whereIn('id',
            $customer->rentals()->distinct()->pluck('user_id')
        )->get();

        return view('admin.customers.show', compact('customer', 'totalRentals', 'completedRentals', 'totalSpent', 'income', 'shopsVisited'));
    }
}
